project:
  type: website

website:
  title: "Internationalization"
  navbar:
    right:
      - about.qmd
      - seminars.qmd
    tools:
      - icon: github
        href: https://github.com/steno-aarhus/internationalization

format:
  html:
    theme: cosmo
    css: styles.css

editor: 
  markdown: 
    wrap: 72
    canonical: true
