project:
  type: sdca-theme

website:
  title: "Proyecto de internacionalización"
  site-url: "https://steno-aarhus.github.io/internationalization/"
  repo-url: "https://github.com/steno-aarhus/internationalization"
  navbar:
    left: 
      - href: calendar.qmd
      - href: seminars.qmd
    tools:
      - icon: github
        href: "https://github.com/steno-aarhus/"
      - icon: twitter
        href: "https://twitter.com/StenoAarhusRes"
      - icon: globe
        href: directory.qmd

format: sdca-theme-html

editor: 
  markdown:
    wrap: 72
    canonical: true
