---
title: "Internationalization of the research strategy at Steno Diabetes Center Aarhus"
subtitle: "Expanding SDCA research networks to the Latin America Region"
---

Although the burden of diabetes increasingly affects people in
low-middle income countries (LMIC), most diabetes research is still
performed in developed countries. This creates a local knowledge gap
that ranges from adequate prevalence and incidence estimates for
diabetes and its complications; expertise in the setup of locally
adapted prevention strategies, and wider processes for state-of-the-art
handling and analysis of complex and large data repositories. This
knowledge gap adds a layer of complexity for implementing solutions to
tackle the burden of diabetes in LMIC contexts.

Through internationalization of research, Steno Diabetes Center Aarhus
(SDCA) aims to position itself in the wider global diabetes community
both by sharing its expertise (outward) as by learning from experiences
elsewhere (inward). SDCA’s current international research network is
heavily oriented to European, Australian, Canadian and US partners. The
overall aim of this project is to broaden the internationalization
research strategy of SDCA by creating and expanding research and
learning networks with institutions from the Latin America Region,
specifically from Mexico, Peru, and Brazil.

This project will initially take mostly a bottom-up approach, fostering
direct educational and research collaboration connections between
researchers. The initiatives will initially be online. As they expand in
the second phase of the project, the consolidation of the networks will
likely increasingly need support from at the organizational level, for
example in the form of letters of intent or collaboration agreements.
The longer term vision is for these collaborative networks to lead to
the establishment of partnerships, joint grant applications and joint
knowledge sharing channels.

The internationalization of the research strategy will be implemented
within a three year time horizon. Each year represents a different stage
in the process with a specific focus within each stage.

Bring the people together. The purpose of this stage is to establish a
network of collaborations that share common ground.

Project development. Once established the international networks, this
stage will aim to develop the basis of joint research projects in the
form of co-authorships, or co-supervision of students. Strengthening the
international collaboration at this stage has the purpose to evolve
partnerships into potential collaborative projects, and grant
co-applications. It will be relevant at this stage to identify potential
funding agencies that could be targeted at a later stage.

Funding co-application & collaborative projects. The aim of this stage
is to submit funding co-applications with the international partners,
and carry out collaborative projects.
